#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user liatening on port 8080
sed -i "s/#user ww-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-avalable/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
